reportportal/agent-Python-RobotFramework

setup.py

This should be merged after new release of https://github.com/reportportal/client-Python

Pull request to update required version for rp python client

---

robotframework_reportportal/model.py

Trim name field to 256 chars max (server limit)

---

.travis.yml

password for PyPi account generated by `travis encrypt --add deploy.password`

 Update PyPi credentials in travis.yml

---

robotframework_reportportal/service.py

fix for [#20](https://github.com/reportportal/agent-Python-RobotFramework/issues/20)
Adding mapping for HTML, WARN, ERROR log levels of RobotFramework.

Log level mapping fix

---

robotframework_reportportal/listener.py
robotframework_reportportal/model.py
robotframework_reportportal/service.py
setup.py

These changes will work in combination with client updates suggested in [this](https://github.com/reportportal/client-Python/pull/62) PR. Please consider this as the temporary solution for reporting to RP v5 via RF. Avoid writing code in the style it's done in that commit.

WIP: Support for V5 changes in client.

---

robotframework_reportportal/listener.py
robotframework_reportportal/model.py
robotframework_reportportal/service.py

This PR fixes the functionality of uploading log messages.

Add item_id to log messages

---

robotframework_reportportal/listener.py

Treat setup/teardown keywords as nested

---

robotframework_reportportal/service.py
setup.py

Change value of the test_item key being sent to the client

---

robotframework_reportportal/model.py

Remove binary literal prefixes from keyword names

---

README.md
robotframework_reportportal/listener.py
robotframework_reportportal/model.py
robotframework_reportportal/variables.py

Allow reporting to an existing launch.

---

README.md
robotframework_reportportal/listener.py
robotframework_reportportal/service.py
robotframework_reportportal/variables.py
setup.py

Fixes 68. 
**Must be released only after 5.0.5 release of the common client.**

Add support for launch and test attributes.

---

requirements.txt
robotframework_reportportal/listener.py
robotframework_reportportal/post_report.py
robotframework_reportportal/service.py
robotframework_reportportal/variables.py

Allow for limiting/setting smaller number of client connections by allowing setting max_pool_size when init_service().

Make use of max_pool_size

---

.gitignore
robotframework_reportportal/listener.py
robotframework_reportportal/post_report.py
robotframework_reportportal/result_visitor.py
robotframework_reportportal/service.py
robotframework_reportportal/time_visitor.py
robotframework_reportportal/variables.py

This should solve:
- #85 when RF's generated report provide the starttime/endtime
- approximation starttime/endtime values when report was modified, eg. [by merge](https://groups.google.com/g/robotframework-users/c/TWvZMtbizrs)

Fix duration

---

robotframework_reportportal/model.py
robotframework_reportportal/service.py

Update models to accomodate RF 4 changes

---

robotframework_reportportal/listener.py
robotframework_reportportal/model.py
robotframework_reportportal/service.py
tests/test_listener.py

Implement support of dynamic attributes

---

robotframework_reportportal/model.py
robotframework_reportportal/service.py
setup.py

Fix sending attachments

---

robotframework_reportportal/model.py
tests/conftest.py
tests/test_model.py

Handle nested setup/teardown keyword correctly

---

robotframework_reportportal/listener.py
robotframework_reportportal/listener.pyi
robotframework_reportportal/logger.py
tests/test_listener.py

Fix for Issue #110 
Also adds a reference on the current listener to be able to log into launch on runtime as here: https://github.com/reportportal/examples-python/blob/master/robotframework/robot/library/LaunchLevelLog.py

Backward compatibility fixes

---

robotframework_reportportal/service.py
robotframework_reportportal/static.py
setup.py

Handle SKIP messages

---

CHANGELOG.md
examples/dynamic_test_case_id.robot
examples/library/Log.py
examples/library/TestCaseId.py
requirements.txt
robotframework_reportportal/model.py
robotframework_reportportal/service.py
tests/integration/test_dynamic_test_case_id.py

Add setting Test Case ID in runtime

[EPMRPP-95894] Add setting Test Case ID in runtime
